import { Timestamp } from 'firebase/firestore';

/**
 * MRTZ Ledger Transaction Types
 */
export type MRTZTransactionType = 
    | 'bet_win' 
    | 'bet_loss' 
    | 'settlement' 
    | 'good_deed' 
    | 'carry_over' 
    | 'adjustment'
    | 'carry_over_resolved';

export type MRTZTransactionStatus = 
    | 'pending' 
    | 'confirmed' 
    | 'settled' 
    | 'carried_over' 
    | 'voided';

export type SettlementType = 
    | 'money' 
    | 'good_deed' 
    | 'agreed_void' 
    | 'partial' 
    | 'carry_over';

export type SettlementStatus = 
    | 'pending' 
    | 'agreed' 
    | 'completed' 
    | 'rejected';

export type GoodDeedType = 
    | 'course_cleanup' 
    | 'help_other_player' 
    | 'community_service' 
    | 'custom';

export type ValidationStatus = 
    | 'pending' 
    | 'approved' 
    | 'rejected';

export type CarryOverStatus = 
    | 'active' 
    | 'resolved' 
    | 'voided';

/**
 * Main Ledger Entry
 */
export interface MRTZLedgerEntry {
    id?: string; // Auto-generated by Firestore
    transactionId: string; // Unique transaction ID
    type: MRTZTransactionType;
    roundId?: string; // Link to round if from betting
    date: Timestamp | Date;
    
    // Parties involved
    fromPlayerId?: string; // Who lost/paid (null for wins, good deeds)
    toPlayerId?: string; // Who won/received (null for losses)
    participants: string[]; // All players involved (for group bets)
    
    // Amounts
    amount: number; // MRTZ amount (positive for wins, negative for losses)
    description: string; // Human-readable description
    
    // Bet details (if from betting)
    betType?: 'skins' | 'nassau' | 'fundatory';
    betDetails?: {
        holeNumber?: number;
        segment?: 'front9' | 'back9' | 'overall';
        carryOverFrom?: number[]; // Previous holes that carried over
        accumulatedValue?: number; // Total value including carryovers
    };
    
    // Settlement details (if settlement)
    settlementType?: SettlementType;
    settlementDetails?: {
        amount?: number; // Actual money if money settlement
        goodDeedId?: string; // Link to good deed if good deed settlement
        validators?: string[]; // Player IDs who validated
        validationStatus?: ValidationStatus;
        photos?: string[]; // URLs of photos for good deeds
    };
    
    // Status
    status: MRTZTransactionStatus;
    settledAt?: Timestamp | Date;
    settledBy?: string; // Player ID who marked as settled
    settlementId?: string; // Link to settlement if part of settlement
    
    // Metadata
    createdAt: Timestamp | Date;
    updatedAt: Timestamp | Date;
    createdBy: string; // Player ID who created entry
}

/**
 * Balance Document (Denormalized for Quick Lookup)
 */
export interface MRTZBalance {
    playerId: string;
    balance: number; // Current total balance (confirmed transactions)
    pendingIn: number; // MRTZ owed to this player (not yet settled)
    pendingOut: number; // MRTZ this player owes (not yet settled)
    lastUpdated: Timestamp | Date;
    transactionCount: number; // Total transactions
    lastTransactionId?: string; // Last transaction ID for reference
}

/**
 * Settlement Agreement
 */
export interface MRTZSettlement {
    id?: string;
    settlementId: string; // Unique settlement ID
    type: SettlementType;
    
    // Parties
    parties: {
        playerId: string;
        role: 'payer' | 'receiver';
        amount: number; // MRTZ amount
        agreed: boolean;
        agreedAt?: Timestamp | Date;
    }[];
    
    // Settlement details
    totalMRTZ: number;
    settlementMethod?: {
        moneyAmount?: number;
        currency?: string; // e.g., 'USD'
        goodDeedId?: string;
        goodDeed?: {
            description: string;
            validators: string[];
            validationStatus: ValidationStatus;
            photos?: string[];
        };
        notes?: string; // Additional notes about settlement
    };
    
    // Status
    status: SettlementStatus;
    agreedAt?: Timestamp | Date;
    completedAt?: Timestamp | Date;
    rejectedAt?: Timestamp | Date;
    rejectedBy?: string;
    rejectionReason?: string;
    
    // Related transactions
    transactionIds: string[]; // Ledger entries this settlement covers
    
    // Metadata
    createdAt: Timestamp | Date;
    createdBy: string;
    updatedAt: Timestamp | Date;
}

/**
 * Carry-Over Bet
 */
export interface MRTZCarryOver {
    id?: string;
    originalRoundId: string;
    originalDate: Timestamp | Date;
    
    // Bet details
    betType: 'skins' | 'nassau';
    betValue: number;
    carryOverDetails: {
        skins?: {
            holes: number[]; // Hole numbers that carried over
            accumulatedValue: number; // Total MRTZ in pot
            tiedPlayers?: string[]; // Players who tied (if applicable)
        };
        nassau?: {
            segments: ('front9' | 'back9' | 'overall')[];
            tiedPlayers: string[];
            segmentScores?: { [segment: string]: { [playerId: string]: number } };
        };
    };
    
    // Players involved
    participants: string[];
    
    // Resolution
    resolvedInRoundId?: string; // Round where it was resolved
    resolvedAt?: Timestamp | Date;
    resolutionType?: 'playoff' | 'split' | 'void' | 'push';
    resolutionDetails?: {
        winners?: { [holeNumber: number]: string }; // For skins playoff
        splitAmounts?: { [playerId: string]: number }; // For split resolution
    };
    
    status: CarryOverStatus;
    createdAt: Timestamp | Date;
    updatedAt: Timestamp | Date;
}

/**
 * Good Deed
 */
export interface MRTZGoodDeed {
    id?: string;
    playerId: string; // Player who did the deed
    deedType: GoodDeedType;
    description: string;
    mrtzValue: number; // MRTZ earned
    
    // Validation
    validators: {
        playerId: string;
        status: ValidationStatus;
        validatedAt?: Timestamp | Date;
        comment?: string;
    }[];
    
    // Evidence
    photos?: string[];
    location?: {
        courseId?: string;
        courseName?: string;
        coordinates?: { lat: number; lng: number };
    };
    
    // Status
    status: 'pending' | 'validated' | 'rejected';
    validatedAt?: Timestamp | Date;
    mrtzAwarded: boolean;
    transactionId?: string; // Link to ledger entry when awarded
    
    // Related settlement (if used to settle debt)
    settlementId?: string;
    
    createdAt: Timestamp | Date;
    createdBy: string;
    updatedAt: Timestamp | Date;
}

/**
 * Outstanding Balance Summary
 */
export interface OutstandingBalance {
    fromPlayerId: string;
    fromPlayerName: string;
    toPlayerId: string;
    toPlayerName: string;
    totalAmount: number; // Total MRTZ owed
    transactionIds: string[]; // Related transactions
    oldestTransactionDate: Date;
    newestTransactionDate: Date;
    canSettle: boolean; // Both players have agreed to settle
}

/**
 * Player MRTZ Summary
 */
export interface PlayerMRTZSummary {
    playerId: string;
    playerName: string;
    currentBalance: number;
    pendingIn: number;
    pendingOut: number;
    netBalance: number; // currentBalance + pendingIn - pendingOut
    totalWon: number; // Lifetime wins
    totalLost: number; // Lifetime losses
    totalSettled: number; // Lifetime settled
    transactionCount: number;
}


